dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  registry:
      id: dubbo-register
      address: "zookeeper://127.0.0.1:2181"
      protocol: "zookeeper"
server:
  port: 8081
