package com.xqy.www.mybatis.mapper;

import com.xqy.www.mybatis.dao.AppTab;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AppTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_tab
     *
     * @mbg.generated
     */
    @Delete({
        "delete from app_tab",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_tab
     *
     * @mbg.generated
     */
    @Insert({
        "insert into app_tab (id, name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(AppTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_tab
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name",
        "from app_tab",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    AppTab selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_tab
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name",
        "from app_tab"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<AppTab> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_tab
     *
     * @mbg.generated
     */
    @Update({
        "update app_tab",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AppTab record);
}