#dubbo:
#  scan:
#    base-packages: com.xqy.www.producer.service
#  application:
#    id: dubbo-provider
#    name: dubbo-provider
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: 20881
#  registry:
#    id: dubbo-register
#    address: "zookeeper://127.0.0.1:2181"
#    protocol: "zookeeper"