#
#mybatis:
#  type-aliases-package: com.xqy.www.mybatis.dao
##  config-location: classpath:mybatisConfig.xml
#  mapper-locations: classpath:mapper/*.xml
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: qq112358
#mapper:
#  mappers: com.xqy.www.mybatis.mapper
##  identity: mysqlspring:
# Base packages to scan Dubbo Components (e.g., @Service, @Reference)

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq112358
