mybatis:
  type-aliases-package: com.xqy.www.producer.dao
#  config-location:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beauty?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 112358
