mybatis:
  type-aliases-package: com.xqy.www.mybatis.dao
#  config-location: classpath:mybatisConfig.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
   map-underscore-to-camel-case: true

mapper:
  mappers: com.xqy.www.mybatis.mapper
  identity: MYSQL
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq112358
